### ISSUE TITLE
Compatability with Crowd 2.8.0

### ISSUE THREAD

**Issue by dovi5988** [greggigon/TeamCity-Crowd-Plugin#10]
Hi,

I understand that as per the docs this is not guaranteed to work with any version of crowd other than 2.6.7. When I try to build based on 2.6.7 it works fine. When I try to build against 2.8.0 it fails. From my limited knowledge it seems that it can not find the dependency "com.atlassian.crowd:crowd-integration-client-rest:2.8.0" which I don't understand because I see it here: https://maven.atlassian.com/content/groups/public/com/atlassian/crowd/crowd-integration-client-rest/

If there are any logs that I can upload that will help you please let me know.

EDIT: If I tell it that the version of crowd is: 2.8.0-releaseplan-m3 then it builds fine. It seems to only be with 2.8.0, 2.8.1 etc.

**Comment by greggigon** [comment]
The crowd distribution is there and Gradle can download it. The problem seems to be in the Crowd Dependencies itself. Looks like it's missing logging library and fails to initialize.

Do you know what is missing?

**Comment by dovi5988** [comment]
greggigon,

What is missing logging libraries? My crowd install or Atlassians site? If I build the plugin for 2.6.7 or 2.8.0-relesaeplan-m3 will that work for me?

**Comment by greggigon** [comment]
The TeamCity Crowd Plugin uses Crowd Client Libraries. It seems that Crowd Client Libraries were shipped with a Logging framework included or different one before. With version you are trying, it reports that Logging library is missing. That is why it cannot build the module.
I will try to get it to work with the latest version of Crowd.

**Comment by bobahspb** [comment]
Build failed for versions:
`     teamCityVersion = '9.1.6'`
`    crowdVersion = '2.8.4'`
`$ java -version`
`java version "1.8.0_73"`
`Java(TM) SE Runtime Environment (build 1.8.0_73-b02)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)`

It would be nice to have working plugin for latest versions of TC and Crowd. Tell me please if I can help you - tests, logs etc. I'm not a programmer, unfortunately. 
Thank you for your job!

**Comment by bjammin** [comment]
Any progress on this?  I'd love to get the plugin working with TC 9.1.6 and Crowd 2.8.4 ... but I'm not a Java dev

**Comment by greggigon** [comment]
Seems like a good soul submitted a pull request with updated dependencies. Try building the plugin now with the latest changes from Master branch.

**Comment by bjammin** [comment]
Thanks for this but I'm not sure how .. never built anything in java before.

Any chance of an updated release on BinTray?
